### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fueko** [aishikaty/tiny-masonry#1]
Tiny-masonry is licensed under the MIT?
I would like to use it in a commercial project.

![zrzut ekranu 2017-03-17 o 19 42 13](https://cloud.githubusercontent.com/assets/23366922/24058019/d84c584a-0b49-11e7-90f4-21501352f54d.png)

**Comment by aishikaty** [comment]
@Kuzoin Hey, I didn't specified it (not sure what's the source of the page). Please feel free to use it, I'm adding WTFPL. Also If you choose to use it I would love to see the outcome.

**Comment by fueko** [comment]
@aishikaty Excelent! Thank you :) 

>>Also If you choose to use it I would love to see the outcome.

Of course :)
