### ISSUE TITLE
add animation

### ISSUE THREAD

**Issue by bUxEE** [aishikaty/tiny-masonry#3]
Any chance you could add transition animation to this wonderful script?

**Comment by aishikaty** [comment]
Hi @bux23,
I believe you are talking about something like [this](https://masonry.desandro.com/options.html#transitionduration)? Sadly that's not something I could add without making the library non-tiny. It's because it doesn't really calculates the absolute positions of the elements.

**Comment by bUxEE** [comment]
Thanks for your fast response.
I actually added simple animations based on animate.css in the fiddle here. https://jsfiddle.net/18rjebz3/3/ This gave a me a wonderful result for my needs!
cheers
